# Generated by Django 2.1.3 on 2019-06-07 12:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cod_prov', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código proveedor')),
                ('cod_sust', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código sustitución')),
                ('notas', models.TextField(blank=True, null=True)),
                ('stock', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stock')),
                ('precio', models.CharField(blank=True, max_length=8, null=True)),
                ('iva', models.IntegerField(blank=True, choices=[(1, 'Iva General (21%)'), (2, 'Iva Reducido (10%)'), (3, 'Iva Superreducido (4%)')], db_index=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacen',
                'ordering': ['-created'],
            },
        ),
    ]
