# Generated by Django 2.1.3 on 2019-06-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
    ]
